# Copyright 2026 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# LiteRT-LM Orchestrator
cmake_minimum_required(VERSION 3.25 FATAL_ERROR)
project(LiteRT-LM-Orchestrator LANGUAGES NONE)

include(ExternalProject)

option(ENABLE_CCACHE "Enables the use of ccache" OFF)
if(${ENABLE_CCACHE} STREQUAL "ON")
  find_program(CCACHE_PROGRAM ccache)
  if(CCACHE_PROGRAM)
      message(STATUS "Using CCache to speed up builds")
      set(CMAKE_C_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
      set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_PROGRAM}")
  else()
      message(WARNING "CCache not found. Install it (`sudo apt install ccache`) for faster builds!")
  endif()
endif()

set(LITERTLM_PROJECT_ROOT "${CMAKE_CURRENT_SOURCE_DIR}" CACHE PATH "LiteRT-LM: Absolute path to the repository root")
set(LITERTLM_TOOLCHAIN_ARGS "" CACHE STRING "String used to define parameterized CMAKE_ARGS")
set(LITERTLM_PREBUILD_DIR "${CMAKE_CURRENT_BINARY_DIR}/prebuild")
set(LITERTLM_PREBUILD_BINARY_DIR "${LITERTLM_PREBUILD_DIR}/build")
set(LITERTLM_PREBUILD_STAMP_DIR "${LITERTLM_PREBUILD_DIR}/stamps")
set(LITERTLM_PREBUILD_TMP_DIR "${LITERTLM_PREBUILD_DIR}/tmp")
set(LITERTLM_PREBUILD_DOWNLOAD_DIR "${LITERTLM_PREBUILD_DIR}/download")
set(LITERTLM_PREBUILD_INSTALL_DIR "${LITERTLM_PREBUILD_DIR}/install")
set(LITERTLM_PREBUILD_EXTERNAL_PROJECT_DIR "${LITERTLM_PREBUILD_BINARY_DIR}/external")
set(LITERTLM_DIR "${CMAKE_CURRENT_BINARY_DIR}/litert_lm")
set(LITERTLM_BINARY_DIR "${LITERTLM_DIR}/build")
set(LITERTLM_STAMP_DIR "${LITERTLM_DIR}/stamps")
set(LITERTLM_TMP_DIR "${LITERTLM_DIR}/tmp")
set(LITERTLM_DOWNLOAD_DIR "${LITERTLM_DIR}/download")
set(LITERTLM_INSTALL_DIR "${LITERTLM_DIR}/install")
set(LITERTLM_PACKAGE_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/cmake/packages/litert_lm")
set(LITERTLM_PREBUILD_TARGETS "absl gtest protobuf flatbuffers")
set(LITERTLM_PREBUILD_EXE "protoc flatc")

# --- Orchestration Logic ---
ExternalProject_Add(
    prebuild
    SOURCE_DIR   "${LITERTLM_PACKAGE_SOURCE_DIR}"
    PREFIX       "${LITERTLM_PREBUILD_DIR}"
    BINARY_DIR   "${LITERTLM_PREBUILD_BINARY_DIR}"
    STAMP_DIR    "${LITERTLM_PREBUILD_STAMP_DIR}"
    TMP_DIR      "${LITERTLM_PREBUILD_TMP_DIR}"
    DOWNLOAD_DIR "${LITERTLM_PREBUILD_DOWNLOAD_DIR}"
    INSTALL_DIR  "${LITERTLM_PREBUILD_INSTALL_DIR}"
    CMAKE_ARGS
        "-DLITERTLM_ORCHESTRATION_PHASE=prebuild"
        "-DLITERTLM_PREBUILD_PHASE=LITERT_PREBUILD_PHASE"
        "-DLITERTLM_PROJECT_ROOT=${LITERTLM_PROJECT_ROOT}"
        "-DLITERTLM_PREBUILD_TARGETS=${LITERTLM_PREBUILD_TARGETS}"
        "-DLITERTLM_PREBUILD_EXTERNAL_PROJECT_DIR=${LITERTLM_PREBUILD_EXTERNAL_PROJECT_DIR}"
        "-DLITERTLM_BUILD_FETCH_CONTENT=OFF"
        "-DLITERTLM_BUILD_EXTERNAL_PROJECTS=OFF"
        "-DLITERTLM_BUILD_TARGETS=OFF"
    INSTALL_COMMAND ""
)

# --- Host Tool Setup ---
if(NOT DEFINED LITERTLM_PREBUILD_PROTOC)
    set(LITERTLM_PREBUILD_PROTOC "${LITERTLM_PREBUILD_EXTERNAL_PROJECT_DIR}/protobuf/install/bin/protoc" CACHE PATH "")
    set(LITERTLM_PREBUILD_PROTOC_BIN_DIR "${LITERTLM_PREBUILD_EXTERNAL_PROJECT_DIR}/protobuf/install/bin" CACHE PATH "")
endif()

if(NOT DEFINED LITERTLM_PREBUILD_FLATC)
    set(LITERTLM_PREBUILD_FLATC "${LITERTLM_PREBUILD_EXTERNAL_PROJECT_DIR}/flatbuffers/install/bin/flatc" CACHE PATH "")
    set(LITERTLM_PREBUILD_FLATC_BIN_DIR "${LITERTLM_PREBUILD_EXTERNAL_PROJECT_DIR}/flatbuffers/install/bin" CACHE PATH "")
endif()

if(DEFINED CMAKE_TOOLCHAIN_FILE)
    set(LITERTLM_TOOLCHAIN_FILE "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}" CACHE PATH "")
endif()

if(DEFINED LITERTLM_TOOLCHAIN_SCRIPT)
    message(STATUS "[LiteRTLM] Executing toolchain script -> ${LITERTLM_TOOLCHAIN_SCRIPT}")
    include("${LITERTLM_TOOLCHAIN_SCRIPT}")
endif()

set(LITERTLM_FBS_DIR "${LITERTLM_PROJECT_ROOT}/schema/core")
set(LITERTLM_FLATBUFFERS_FILES "litertlm_header_schema.fbs")

ExternalProject_Add(
    litert_lm
    DEPENDS      prebuild
    SOURCE_DIR   "${LITERTLM_PACKAGE_SOURCE_DIR}"
    PREFIX       "${LITERTLM_DIR}"
    BINARY_DIR   "${LITERTLM_BINARY_DIR}"
    STAMP_DIR    "${LITERTLM_STAMP_DIR}"
    TMP_DIR      "${LITERTLM_TMP_DIR}"
    DOWNLOAD_DIR "${LITERTLM_DOWNLOAD_DIR}"
    INSTALL_DIR  "${LITERTLM_INSTALL_DIR}"
    PATCH_COMMAND
        ${CMAKE_COMMAND} -E echo "[LiteRTLM] Generating FlatBuffers headers for LiteRT-LM..."
        COMMAND ${LITERTLM_PREBUILD_FLATC} --cpp
        --gen-object-api --reflect-names
        --gen-mutable -o "${LITERTLM_FBS_DIR}"
        "${LITERTLM_FBS_DIR}/${LITERTLM_FLATBUFFERS_FILES}"
    CMAKE_ARGS
        ${LITERTLM_TOOLCHAIN_ARGS}
        ${LITERTLM_TOOLCHAIN_FILE}
        "-DLITERTLM_TOOLCHAIN_FILE=${LITERTLM_TOOLCHAIN_FILE}"
        "-DLITERTLM_TOOLCHAIN_ARGS=${LITERTLM_TOOLCHAIN_ARGS}"
        "-DLITERTLM_ORCHESTRATION_PHASE=litert_lm"
        "-DLITERTLM_TARGET_PHASE=litert_lm"
        "-DLITERTLM_PROJECT_ROOT=${LITERTLM_PROJECT_ROOT}"
        "-DLITERTLM_HOST_PROTOC=${LITERTLM_PREBUILD_PROTOC}"
        "-DLITERTLM_HOST_PROTOC_BIN_DIR=${LITERTLM_PREBUILD_PROTOC_BIN_DIR}"
        "-DLITERTLM_HOST_FLATC=${LITERTLM_PREBUILD_FLATC}"
        "-DLITERTLM_HOST_FLATC_BIN_DIR=${LITERTLM_PREBUILD_FLATC_BIN_DIR}"
        "-DLITERTLM_PREBUILD_TARGETS=${LITERTLM_PREBUILD_TARGETS}"
        "-DLITERTLM_PREBUILD_EXTERNAL_PROJECT_DIR=${LITERTLM_PREBUILD_EXTERNAL_PROJECT_DIR}"
        "-DLITERTLM_BUILD_FETCH_CONTENT=ON"
        "-DLITERTLM_BUILD_EXTERNAL_PROJECTS=ON"
        "-DLITERTLM_BUILD_TARGETS=ON"
        "-DCMAKE_CXX_FLAGS=-w"
    INSTALL_COMMAND ""
    BUILD_ALWAYS TRUE
)
